-- Convenience script: every file in this directory, concatenated in
-- dependency order, unmodified. Paste this whole file into the Supabase
-- SQL editor and run it once.
--
-- Safe to run against a project at ANY prior migration state - every
-- statement in every section below is idempotent (create table if not
-- exists, add column if not exists, drop policy if exists + create
-- policy), so running this on a project that already has some or all of
-- these applied will not duplicate or error on anything already there.
--
-- Source order: profiles -> workspaces -> clients -> projects -> tasks ->
-- tags -> client_interaction_logs -> reports -> activity_log ->
-- task_subtasks -> task_comments (matches the "run after" dependency
-- comments in each individual file).
--
-- This file is generated by hand from the individual files below - if you
-- change one of them, regenerate this one to match (or just run the
-- individual files instead).

-- ============================================================
-- profiles.sql
-- ============================================================

-- Run this in your Supabase project's SQL editor before testing sign-up
-- end-to-end (feature 1a, step 7). Steps 1-6 don't need it.
--
-- If you already ran an earlier version of this file, everything here is
-- safe to re-run - the table/policy statements are idempotent, and the new
-- "Auto-create profile on signup" section is what you actually need now.

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null,
  avatar_url text,
  theme_preference text not null default 'light' check (theme_preference in ('light', 'dark')),
  created_at timestamptz not null default now()
);

alter table profiles enable row level security;

-- Profiles are created by the trigger below (SECURITY DEFINER, bypasses
-- RLS), not by the client, so there is no insert policy.
drop policy if exists "Users can insert their own profile" on profiles;

-- Expanded in feature 9 from "you can see your own profile" to "you can see
-- your own profile, or anyone's who shares a workspace with you" - needed to
-- show fellow members' names in the assignee picker.
--
-- Uses the same SECURITY DEFINER pattern as workspaces.sql's
-- is_workspace_member: the membership check runs in a function that bypasses
-- RLS internally, so reading workspace_members from inside this policy can't
-- recurse into workspace_members' own select policy.
create or replace function public.shares_workspace_with(target_user_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from workspace_members wm1
    join workspace_members wm2 on wm1.workspace_id = wm2.workspace_id
    where wm1.user_id = auth.uid()
    and wm2.user_id = target_user_id
  );
$$;

grant execute on function public.shares_workspace_with(uuid) to authenticated;

drop policy if exists "Users can view their own profile" on profiles;
drop policy if exists "Users can view profiles of their workspace members" on profiles;
create policy "Users can view profiles of their workspace members"
  on profiles for select
  using (
    auth.uid() = id
    or public.shares_workspace_with(id)
  );

drop policy if exists "Users can update their own profile" on profiles;
create policy "Users can update their own profile"
  on profiles for update
  using (auth.uid() = id);

-- Auto-create profile on signup, server-side. A client-side insert
-- immediately after supabase.auth.signUp() fails whenever "Confirm email" is
-- on, because there is no session (and therefore no auth.uid()) until the
-- user confirms. This trigger fires when the auth user row is created,
-- independent of session state.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, theme_preference)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', new.email),
    'light'
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

alter table profiles add column if not exists notify_assigned_to_me boolean not null default true;
alter table profiles add column if not exists notify_mentions boolean not null default true;
alter table profiles add column if not exists notify_due_soon boolean not null default true;
alter table profiles add column if not exists notify_project_activity boolean not null default false;
alter table profiles add column if not exists notify_product_news boolean not null default false;

-- ============================================================
-- workspaces.sql
-- ============================================================

create table if not exists workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists workspace_members (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('Admin', 'Editor', 'Viewer')),
  joined_at timestamptz not null default now(),
  unique (workspace_id, user_id)
);

alter table workspaces enable row level security;
alter table workspace_members enable row level security;

-- No insert policy: creation goes through create_workspace below
-- (SECURITY DEFINER, bypasses RLS), the same atomic-write pattern
-- profiles.sql's handle_new_user trigger established. Renaming (update) is a
-- single-row write, so it doesn't need that treatment - see the Admin-only
-- update policy near the bottom of this file.
drop policy if exists "Members can view their workspaces" on workspaces;
create policy "Members can view their workspaces"
  on workspaces for select
  using (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = workspaces.id
      and workspace_members.user_id = auth.uid()
    )
  );

-- Expanded in feature 9 from "you can see your own row" to "you can see
-- every member of a workspace you belong to" - needed for the assignee
-- picker to list a workspace's members, not just the caller's own row.
--
-- A plain `exists (select 1 from workspace_members ...)` subquery here would
-- reference the very table the policy protects, which Postgres evaluates by
-- re-applying this same policy to the subquery - infinite recursion
-- (confirmed live: query failed with "infinite recursion detected in policy
-- for relation workspace_members"). The fix is the same SECURITY DEFINER
-- pattern already used by handle_new_user and create_workspace: the check
-- runs in a function that bypasses RLS internally, so the policy never
-- re-triggers itself.
create or replace function public.is_workspace_member(target_workspace_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from workspace_members
    where workspace_id = target_workspace_id
    and user_id = auth.uid()
  );
$$;

grant execute on function public.is_workspace_member(uuid) to authenticated;

drop policy if exists "Users can view their own membership rows" on workspace_members;
drop policy if exists "Members can view their workspace's membership rows" on workspace_members;
create policy "Members can view their workspace's membership rows"
  on workspace_members for select
  using (public.is_workspace_member(workspace_id));

-- Only the workspace's Admin can rename it. No Editor/Viewer members can
-- exist yet (feature 11 adds that), but this policy is written now so
-- feature 11 doesn't have to retrofit it - see feature 2c.
drop policy if exists "Admins can update their workspace" on workspaces;
create policy "Admins can update their workspace"
  on workspaces for update
  using (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = workspaces.id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role = 'Admin'
    )
  );

create or replace function public.create_workspace(workspace_name text)
returns workspaces
language plpgsql
security definer set search_path = public
as $$
declare
  new_workspace workspaces;
begin
  if trim(workspace_name) = '' then
    raise exception 'Workspace name is required';
  end if;

  insert into workspaces (name, owner_id)
  values (trim(workspace_name), auth.uid())
  returning * into new_workspace;

  insert into workspace_members (workspace_id, user_id, role)
  values (new_workspace.id, auth.uid(), 'Admin');

  return new_workspace;
end;
$$;

grant execute on function public.create_workspace(text) to authenticated;

-- Feature 11a: add/remove workspace members. Both writes go through these
-- SECURITY DEFINER RPCs rather than raw insert/delete policies on
-- workspace_members - add_workspace_member needs to bypass profiles' RLS to
-- look up an invitee who doesn't share a workspace with the caller yet, and
-- routing remove the same way keeps both the authorization check and the
-- last-Admin guard in one place with a clear raised error, instead of a
-- silent RLS-denied no-op.
create or replace function public.is_workspace_admin(target_workspace_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from workspace_members
    where workspace_id = target_workspace_id
    and user_id = auth.uid()
    and role = 'Admin'
  );
$$;

grant execute on function public.is_workspace_admin(uuid) to authenticated;

create or replace function public.add_workspace_member(
  target_workspace_id uuid,
  member_email text,
  member_role text
)
returns workspace_members
language plpgsql
security definer set search_path = public
as $$
declare
  target_user_id uuid;
  new_member workspace_members;
begin
  if not public.is_workspace_admin(target_workspace_id) then
    raise exception 'Only a workspace Admin can add members';
  end if;

  if member_role not in ('Admin', 'Editor', 'Viewer') then
    raise exception 'Invalid role';
  end if;

  select id into target_user_id from profiles where email = member_email;
  if target_user_id is null then
    raise exception 'No account found with that email';
  end if;

  if exists (
    select 1 from workspace_members
    where workspace_id = target_workspace_id and user_id = target_user_id
  ) then
    raise exception 'This person is already a member of this workspace';
  end if;

  insert into workspace_members (workspace_id, user_id, role)
  values (target_workspace_id, target_user_id, member_role)
  returning * into new_member;

  return new_member;
end;
$$;

grant execute on function public.add_workspace_member(uuid, text, text) to authenticated;

create or replace function public.remove_workspace_member(
  target_workspace_id uuid,
  target_user_id uuid
)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  admin_count int;
begin
  if not public.is_workspace_admin(target_workspace_id) then
    raise exception 'Only a workspace Admin can remove members';
  end if;

  select count(*) into admin_count
  from workspace_members
  where workspace_id = target_workspace_id and role = 'Admin';

  if admin_count <= 1 and exists (
    select 1 from workspace_members
    where workspace_id = target_workspace_id
    and user_id = target_user_id
    and role = 'Admin'
  ) then
    raise exception 'Cannot remove the last Admin of a workspace';
  end if;

  delete from workspace_members
  where workspace_id = target_workspace_id and user_id = target_user_id;
end;
$$;

grant execute on function public.remove_workspace_member(uuid, uuid) to authenticated;

-- ============================================================
-- clients.sql
-- ============================================================

create table if not exists clients (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references workspaces(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  company text,
  website text,
  created_at timestamptz not null default now()
);

alter table clients enable row level security;

drop policy if exists "Members can view their workspace's clients" on clients;
create policy "Members can view their workspace's clients"
  on clients for select
  using (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = clients.workspace_id
      and workspace_members.user_id = auth.uid()
    )
  );

-- Role-gated from the start (feature 11b already exists) - no "launch
-- open, retrofit later" step needed here, unlike feature 10's tags.
drop policy if exists "Editors can create clients in their workspace" on clients;
create policy "Editors can create clients in their workspace"
  on clients for insert
  with check (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = clients.workspace_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );

-- Feature 36d: client creation modal - industry/owner/relationship/notes
-- fields. owner_id references auth.users, matching tasks.assignee_id and
-- projects.owner_id's existing convention (not profiles). No RLS changes
-- needed - the insert/select policies above are row-level, not
-- column-scoped, so they already cover these columns.
alter table clients add column if not exists industry text;
alter table clients add column if not exists owner_id uuid references auth.users(id) on delete set null;
alter table clients add column if not exists relationship text not null default 'Prospect' check (relationship in ('Active', 'Prospect', 'Churned'));
alter table clients add column if not exists notes text;

-- ============================================================
-- projects.sql
-- ============================================================

create table if not exists projects (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references workspaces(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

alter table projects enable row level security;

-- Run this after supabase/clients.sql (client_id references clients).
alter table projects add column if not exists client_id uuid references clients(id) on delete set null;

drop policy if exists "Members can view their workspace's projects" on projects;
create policy "Members can view their workspace's projects"
  on projects for select
  using (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = projects.workspace_id
      and workspace_members.user_id = auth.uid()
    )
  );

-- Role-gated from the start (unlike tags, which launched before feature
-- 11b's role enforcement existed and needed a follow-up pass). No delete
-- policy yet.
drop policy if exists "Editors can create projects in their workspace" on projects;
create policy "Editors can create projects in their workspace"
  on projects for insert
  with check (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = projects.workspace_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );

-- Feature 34d: status/description columns. This update policy exists so a
-- future feature can let a project's status change - nothing in the app
-- writes to `status` yet, every project stays at its 'Active' default.
alter table projects add column if not exists status text not null default 'Active' check (status in ('Active', 'Completed', 'Archived'));
alter table projects add column if not exists description text;

drop policy if exists "Editors can update their workspace's projects" on projects;
create policy "Editors can update their workspace's projects"
  on projects for update
  using (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = projects.workspace_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );

-- Feature 36c: project creation modal - owner/schedule/label fields.
-- owner_id references auth.users, matching tasks.assignee_id's existing
-- convention (not profiles) for the same kind of "assigned member" field.
-- No RLS changes needed - the insert/update policies above are row-level,
-- not column-scoped, so they already cover these columns.
alter table projects add column if not exists owner_id uuid references auth.users(id) on delete set null;
alter table projects add column if not exists start_date date;
alter table projects add column if not exists target_date date;
alter table projects add column if not exists label_color text not null default 'gray' check (label_color in ('gray', 'red', 'orange', 'green', 'blue', 'purple'));

-- Feature 39: deal value. deal_currency always has a value (even when
-- deal_value is null) so a set deal_value is never missing its unit.
alter table projects add column if not exists deal_value numeric;
alter table projects add column if not exists deal_currency text not null default 'USD' check (deal_currency in ('USD', 'KES', 'AED'));

-- ============================================================
-- project_members.sql
-- ============================================================

create table if not exists project_members (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (project_id, user_id)
);

alter table project_members enable row level security;

drop policy if exists "Members can view their workspace's project members" on project_members;
create policy "Members can view their workspace's project members"
  on project_members for select
  using (
    exists (
      select 1 from projects
      join workspace_members on workspace_members.workspace_id = projects.workspace_id
      where projects.id = project_members.project_id
      and workspace_members.user_id = auth.uid()
    )
  );

-- No update/delete policy yet - nothing in feature 38 edits or removes
-- membership after creation (see current-feature.md's Out of scope).
drop policy if exists "Editors can add project members in their workspace" on project_members;
create policy "Editors can add project members in their workspace"
  on project_members for insert
  with check (
    exists (
      select 1 from projects
      join workspace_members on workspace_members.workspace_id = projects.workspace_id
      where projects.id = project_members.project_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );

-- ============================================================
-- tasks.sql
-- ============================================================

create table if not exists tasks (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references workspaces(id) on delete cascade,
  title text not null,
  description text,
  priority text not null default 'Medium' check (priority in ('High', 'Medium', 'Low')),
  status text not null default 'Todo' check (status in ('Todo', 'In Progress', 'Blocked', 'Waiting', 'Done')),
  due_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table tasks add column if not exists assignee_id uuid references auth.users(id) on delete set null;

-- Feature 19: { frequency: 'Daily' | 'Weekly' | 'Monthly', interval: number,
-- endDate: string | null }, or null for a non-recurring task. Shape is
-- validated client-side (validateRecurrenceRule.js), not by a DB constraint.
alter table tasks add column if not exists recurrence_rule jsonb;

-- Feature 20a: suppresses overdue/today/upcoming urgency signals until
-- this passes, without changing due_at (see isTaskSnoozed.js).
alter table tasks add column if not exists snoozed_until timestamptz;

-- Run this after supabase/projects.sql (project_id references projects).
alter table tasks add column if not exists project_id uuid references projects(id) on delete set null;

-- Run this after supabase/clients.sql (client_id references clients).
alter table tasks add column if not exists client_id uuid references clients(id) on delete set null;

alter table tasks enable row level security;

drop policy if exists "Members can view their workspace's tasks" on tasks;
create policy "Members can view their workspace's tasks"
  on tasks for select
  using (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = tasks.workspace_id
      and workspace_members.user_id = auth.uid()
    )
  );

-- Feature 11b: Admin and Editor can write; Viewer is read-only (select above
-- stays unrestricted). Extends the existing cross-table workspace_members
-- check already on these policies - no new helper needed, no recursion risk
-- (this table isn't subquerying itself).
drop policy if exists "Members can create tasks in their workspace" on tasks;
drop policy if exists "Editors can create tasks in their workspace" on tasks;
create policy "Editors can create tasks in their workspace"
  on tasks for insert
  with check (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = tasks.workspace_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );

drop policy if exists "Members can update their workspace's tasks" on tasks;
drop policy if exists "Editors can update their workspace's tasks" on tasks;
create policy "Editors can update their workspace's tasks"
  on tasks for update
  using (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = tasks.workspace_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );

drop policy if exists "Members can delete their workspace's tasks" on tasks;
drop policy if exists "Editors can delete their workspace's tasks" on tasks;
create policy "Editors can delete their workspace's tasks"
  on tasks for delete
  using (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = tasks.workspace_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );

-- 3b needs this once edits exist; cheap to add alongside the table now.
create or replace function public.set_tasks_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tasks_set_updated_at on tasks;
create trigger tasks_set_updated_at
  before update on tasks
  for each row execute function public.set_tasks_updated_at();

-- ============================================================
-- tags.sql
-- ============================================================

create table if not exists tags (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references workspaces(id) on delete cascade,
  name text not null,
  color text not null default 'gray' check (color in ('gray', 'red', 'orange', 'green', 'blue', 'purple')),
  created_at timestamptz not null default now()
);

create unique index if not exists tags_workspace_id_lower_name_idx
  on tags (workspace_id, lower(name));

create table if not exists task_tags (
  task_id uuid not null references tasks(id) on delete cascade,
  tag_id uuid not null references tags(id) on delete cascade,
  primary key (task_id, tag_id)
);

alter table tags enable row level security;
alter table task_tags enable row level security;

-- Same non-recursive workspace_members check tasks.sql already uses. No
-- SECURITY DEFINER helper needed here (unlike workspaces.sql's feature 9
-- fix) - that recursion only happens when a policy subqueries its own
-- table; tags and task_tags each query a different table than themselves.
drop policy if exists "Members can view their workspace's tags" on tags;
create policy "Members can view their workspace's tags"
  on tags for select
  using (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = tags.workspace_id
      and workspace_members.user_id = auth.uid()
    )
  );

-- Feature 11b: Admin and Editor can write; Viewer is read-only (select
-- above stays unrestricted).
drop policy if exists "Members can create tags in their workspace" on tags;
drop policy if exists "Editors can create tags in their workspace" on tags;
create policy "Editors can create tags in their workspace"
  on tags for insert
  with check (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = tags.workspace_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );

-- task_tags has no workspace_id of its own, so these scope through the
-- referenced task's workspace instead.
drop policy if exists "Members can view their workspace's task tags" on task_tags;
create policy "Members can view their workspace's task tags"
  on task_tags for select
  using (
    exists (
      select 1 from tasks
      join workspace_members on workspace_members.workspace_id = tasks.workspace_id
      where tasks.id = task_tags.task_id
      and workspace_members.user_id = auth.uid()
    )
  );

-- Feature 11b: Admin and Editor can write; Viewer is read-only.
drop policy if exists "Members can tag tasks in their workspace" on task_tags;
drop policy if exists "Editors can tag tasks in their workspace" on task_tags;
create policy "Editors can tag tasks in their workspace"
  on task_tags for insert
  with check (
    exists (
      select 1 from tasks
      join workspace_members on workspace_members.workspace_id = tasks.workspace_id
      where tasks.id = task_tags.task_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );

drop policy if exists "Members can untag tasks in their workspace" on task_tags;
drop policy if exists "Editors can untag tasks in their workspace" on task_tags;
create policy "Editors can untag tasks in their workspace"
  on task_tags for delete
  using (
    exists (
      select 1 from tasks
      join workspace_members on workspace_members.workspace_id = tasks.workspace_id
      where tasks.id = task_tags.task_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );

-- ============================================================
-- client_interaction_logs.sql
-- ============================================================

create table if not exists client_interaction_logs (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references clients(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  note text not null,
  occurred_at timestamptz not null default now()
);

alter table client_interaction_logs enable row level security;

-- client_interaction_logs has no workspace_id of its own, so these scope
-- through the referenced client's workspace instead - same pattern
-- task_tags.sql uses for scoping through tasks.
drop policy if exists "Members can view their workspace's client interaction logs" on client_interaction_logs;
create policy "Members can view their workspace's client interaction logs"
  on client_interaction_logs for select
  using (
    exists (
      select 1 from clients
      join workspace_members on workspace_members.workspace_id = clients.workspace_id
      where clients.id = client_interaction_logs.client_id
      and workspace_members.user_id = auth.uid()
    )
  );

-- Role-gated like every other content write since feature 11b, plus a
-- self-authorship check (author_id = auth.uid()) so an Editor can't log
-- an interaction as someone else - a distinct property from the role
-- check, verified separately.
drop policy if exists "Editors can log interactions for their workspace's clients" on client_interaction_logs;
create policy "Editors can log interactions for their workspace's clients"
  on client_interaction_logs for insert
  with check (
    author_id = auth.uid()
    and exists (
      select 1 from clients
      join workspace_members on workspace_members.workspace_id = clients.workspace_id
      where clients.id = client_interaction_logs.client_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );

-- ============================================================
-- reports.sql
-- ============================================================

create table if not exists reports (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references workspaces(id) on delete cascade,
  type text not null check (type in ('project-status', 'task-completion')),
  format text not null check (format in ('csv', 'pdf')),
  period_start date not null,
  period_end date not null,
  generated_at timestamptz not null default now()
);

alter table reports enable row level security;

-- Unlike every other table's insert policy (clients, projects, tasks - all
-- Admin/Editor only), this one is open to every workspace member. Exporting
-- a report doesn't mutate any CRM content a Viewer can't already see on
-- screen - it's a read/output action, not a write to task/project/client
-- data - so there's no reason to block Viewer from downloading the same
-- numbers they're already allowed to view.
drop policy if exists "Members can view their workspace's reports" on reports;
create policy "Members can view their workspace's reports"
  on reports for select
  using (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = reports.workspace_id
      and workspace_members.user_id = auth.uid()
    )
  );

drop policy if exists "Members can log reports in their workspace" on reports;
create policy "Members can log reports in their workspace"
  on reports for insert
  with check (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = reports.workspace_id
      and workspace_members.user_id = auth.uid()
    )
  );

-- ============================================================
-- activity_log.sql
-- ============================================================

create table if not exists activity_log (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references workspaces(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  summary text not null,
  entity_type text,
  entity_id uuid,
  occurred_at timestamptz not null default now()
);

alter table activity_log enable row level security;

-- Open to every workspace member, like reports.sql - logging an activity
-- isn't a content mutation a role should be able to block, it's a
-- byproduct of actions every role can already take (or already see).
drop policy if exists "Members can view their workspace's activity" on activity_log;
create policy "Members can view their workspace's activity"
  on activity_log for select
  using (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = activity_log.workspace_id
      and workspace_members.user_id = auth.uid()
    )
  );

drop policy if exists "Members can log activity in their workspace" on activity_log;
create policy "Members can log activity in their workspace"
  on activity_log for insert
  with check (
    exists (
      select 1 from workspace_members
      where workspace_members.workspace_id = activity_log.workspace_id
      and workspace_members.user_id = auth.uid()
    )
  );

-- ============================================================
-- task_subtasks.sql
-- ============================================================

create table if not exists task_subtasks (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references tasks(id) on delete cascade,
  title text not null,
  is_done boolean not null default false,
  position integer not null,
  created_at timestamptz not null default now()
);

alter table task_subtasks enable row level security;

drop policy if exists "Members can view their workspace's task subtasks" on task_subtasks;
create policy "Members can view their workspace's task subtasks"
  on task_subtasks for select
  using (
    exists (
      select 1 from tasks
      join workspace_members on workspace_members.workspace_id = tasks.workspace_id
      where tasks.id = task_subtasks.task_id
      and workspace_members.user_id = auth.uid()
    )
  );

drop policy if exists "Editors can add subtasks to tasks in their workspace" on task_subtasks;
create policy "Editors can add subtasks to tasks in their workspace"
  on task_subtasks for insert
  with check (
    exists (
      select 1 from tasks
      join workspace_members on workspace_members.workspace_id = tasks.workspace_id
      where tasks.id = task_subtasks.task_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );

drop policy if exists "Editors can update subtasks on tasks in their workspace" on task_subtasks;
create policy "Editors can update subtasks on tasks in their workspace"
  on task_subtasks for update
  using (
    exists (
      select 1 from tasks
      join workspace_members on workspace_members.workspace_id = tasks.workspace_id
      where tasks.id = task_subtasks.task_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  )
  with check (
    exists (
      select 1 from tasks
      join workspace_members on workspace_members.workspace_id = tasks.workspace_id
      where tasks.id = task_subtasks.task_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );

drop policy if exists "Editors can remove subtasks from tasks in their workspace" on task_subtasks;
create policy "Editors can remove subtasks from tasks in their workspace"
  on task_subtasks for delete
  using (
    exists (
      select 1 from tasks
      join workspace_members on workspace_members.workspace_id = tasks.workspace_id
      where tasks.id = task_subtasks.task_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );

-- ============================================================
-- task_comments.sql
-- ============================================================

create table if not exists task_comments (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references tasks(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

alter table task_comments enable row level security;

drop policy if exists "Members can view their workspace's task comments" on task_comments;
create policy "Members can view their workspace's task comments"
  on task_comments for select
  using (
    exists (
      select 1 from tasks
      join workspace_members on workspace_members.workspace_id = tasks.workspace_id
      where tasks.id = task_comments.task_id
      and workspace_members.user_id = auth.uid()
    )
  );

drop policy if exists "Editors can comment on tasks in their workspace" on task_comments;
create policy "Editors can comment on tasks in their workspace"
  on task_comments for insert
  with check (
    author_id = auth.uid()
    and exists (
      select 1 from tasks
      join workspace_members on workspace_members.workspace_id = tasks.workspace_id
      where tasks.id = task_comments.task_id
      and workspace_members.user_id = auth.uid()
      and workspace_members.role in ('Admin', 'Editor')
    )
  );
